var DicArray=[]; DicArray.push({eng: "time", trk: "|ˈtaɪm|", ukr: "час", rus: "время", snd: "time.mp3"});
DicArray.push({eng: "second", trk: "|ˈsekənd|", ukr: "секунда", rus: "секунда", snd: "second.mp3"});
DicArray.push({eng: "minute", trk: "|ˈmɪnɪt|", ukr: "минута", rus: "минута", snd: "minute.mp3"});
DicArray.push({eng: "hour", trk: "|ˈaʊə|", ukr: "година", rus: "час", snd: "hour.mp3"});
DicArray.push({eng: "day", trk: "|deɪ|", ukr: "день", rus: "день", snd: "day.mp3"});
DicArray.push({eng: "daytime", trk: "|ˈdeɪtʌɪm|", ukr: "денний час", rus: "дневное время", snd: "daytime.mp3"});
DicArray.push({eng: "midnight", trk: "|ˈmɪdnʌɪt|", ukr: "опівночі", rus: "полночь", snd: "midnight.mp3"});
DicArray.push({eng: "week", trk: "|wiːk|", ukr: "тиждень", rus: "неделя", snd: "week.mp3"});
DicArray.push({eng: "weekday", trk: "|ˈwiːkdeɪ|", ukr: "робочий день", rus: "будний день", snd: "weekday.mp3"});
DicArray.push({eng: "weekend", trk: "|wiːkˈɛnd|", ukr: "вихідні", rus: "уик-энд", snd: "weekend.mp3"});
DicArray.push({eng: "day off", trk: "|deɪ  ɔːf|", ukr: "вихідний", rus: "выходной день", snd: "day off.mp3"});
DicArray.push({eng: "month", trk: "|mʌnθ|", ukr: "місяць", rus: "месяц", snd: "month.mp3"});
DicArray.push({eng: "season", trk: "|ˈsiːzn|", ukr: "сезон", rus: "сезон", snd: "season.mp3"});
DicArray.push({eng: "year", trk: "|ˈjiə|", ukr: "рік", rus: "год", snd: "year.mp3"});
DicArray.push({eng: "holiday", trk: "|ˈhɒlɪdeɪ|", ukr: "свято", rus: "праздник", snd: "holiday.mp3"});
DicArray.push({eng: "vacation and holidays", trk: "|vəˈkeɪʃn ænd ˈhɒl.ɪ.deɪ|", ukr: "канікули і святкові", rus: "каникулии и праздничные дни", snd: "vacation and holidays.mp3"});
DicArray.push({eng: "century", trk: "|ˈsɛntʃʊri|", ukr: "століття", rus: "столетие", snd: "century.mp3"});
DicArray.push({eng: "tomorrow", trk: "|təˈmɒrəʊ|", ukr: "завтра", rus: "завтра", snd: "tomorrow.mp3"});
DicArray.push({eng: "today", trk: "|təˈdeɪ|", ukr: "сьогодні", rus: "сегодня", snd: "today.mp3"});
DicArray.push({eng: "yesterday", trk: "|ˈjɛstədeɪ|", ukr: "вчора", rus: "вчера", snd: "yesterday.mp3"});
DicArray.push({eng: "tonight", trk: "|təˈnʌɪt|", ukr: "сьогодні ввечері", rus: "сегодня вечером", snd: "tonight.mp3"});
DicArray.push({eng: "Monday", trk: "|ˈmʌndeɪ|", ukr: "понеділок", rus: "понедельник", snd: "Monday.mp3"});
DicArray.push({eng: "Tuesday", trk: "|ˈtjuːzdeɪ|", ukr: "вівторок", rus: "вторник", snd: "Tuesday.mp3"});
DicArray.push({eng: "Wednesday", trk: "|ˈwɛnzdeɪ|", ukr: "середа", rus: "среда", snd: "Wednesday.mp3"});
DicArray.push({eng: "Thursday", trk: "|ˈθəːzdeɪ|", ukr: "четвер", rus: "четверг", snd: "Thursday.mp3"});
DicArray.push({eng: "Friday", trk: "|ˈfrʌɪdeɪ|", ukr: "п'ятниця", rus: "пятница", snd: "Friday.mp3"});
DicArray.push({eng: "Saturday", trk: "|ˈsatədeɪ|", ukr: "субота", rus: "суббота", snd: "Saturday.mp3"});