var DicArray=[]; DicArray.push({eng: "January", trk: "|ˈdʒænjueri|", ukr: "січень", rus: "январь", snd: "January.mp3"});
DicArray.push({eng: "February", trk: "|ˈfebrueri|", ukr: "лютий", rus: "февраль", snd: "February.mp3"});
DicArray.push({eng: "March", trk: "|mɑːtʃ|", ukr: "березень", rus: "март", snd: "March.mp3"});
DicArray.push({eng: "April", trk: "|ˈeɪprəl|", ukr: "квітень", rus: "апрель", snd: "April.mp3"});
DicArray.push({eng: "May", trk: "|meɪ|", ukr: "травень", rus: "май", snd: "May.mp3"});
DicArray.push({eng: "June", trk: "|dʒuːn|", ukr: "червень", rus: "июнь", snd: "June.mp3"});
DicArray.push({eng: "July", trk: "|dʒuːˈlaɪ|", ukr: "липень", rus: "июль", snd: "July.mp3"});
DicArray.push({eng: "August", trk: "|ɔːˈɡʌst|", ukr: "серпень", rus: "август", snd: "August.mp3"});
DicArray.push({eng: "September", trk: "|sɛpˈtɛmbə|", ukr: "вересень", rus: "сентябрь", snd: "September.mp3"});
DicArray.push({eng: "October", trk: "|ɒkˈtəʊbə|", ukr: "жовтень", rus: "октябрь", snd: "October.mp3"});
DicArray.push({eng: "November", trk: "|noʊˈvembər|", ukr: "листопад", rus: "ноябрь", snd: "November.mp3"});
DicArray.push({eng: "December", trk: "|dɪˈsɛmbə|", ukr: "грудень", rus: "декабрь", snd: "December.mp3"});
DicArray.push({eng: "winter", trk: "|ˈwɪntər |", ukr: "зима", rus: "зима", snd: "winter.mp3"});
DicArray.push({eng: "spring", trk: "|sprɪŋ|", ukr: "весна", rus: "весна", snd: "spring.mp3"});
DicArray.push({eng: "summer", trk: "|ˈsʌmər |", ukr: "літо", rus: "лето", snd: "summer.mp3"});
DicArray.push({eng: "autumn", trk: "|ˈɔːtəm |", ukr: "осінь", rus: "осень", snd: "autumn.mp3"});
DicArray.push({eng: "Christmas", trk: "|ˈkrɪs.məs|", ukr: "Різдво", rus: "Рождество", snd: "Christmas.mp3"});
DicArray.push({eng: "New year", trk: "|nuː jɜː(r)|", ukr: "Новий рік", rus: "Новый год", snd: "New year.mp3"});
DicArray.push({eng: "Birthday", trk: "|ˈbɜːrθdeɪ |", ukr: "День народження", rus: "День рождения", snd: "Birthday.mp3"});
DicArray.push({eng: "o`clock", trk: "|əˈklɒk|", ukr: "на годиннику", rus: "на часах", snd: "o`clock.mp3"});
DicArray.push({eng: "in the morning", trk: "|ɪn ðə ˈmɔːrnɪŋ|", ukr: "вранці", rus: "утром ", snd: "in the morning.mp3"});
DicArray.push({eng: "in the evening", trk: "|ɪn ðə ˈiːvnɪŋ|", ukr: "ввечері", rus: "вечером", snd: "in the evening.mp3"});
DicArray.push({eng: "in the afternoon", trk: "|ɪn ðə ˌæftərˈnuːn|", ukr: "вдень", rus: "послеобеденное время", snd: "in the afternoon.mp3"});
DicArray.push({eng: "at night", trk: "|ət naɪt|", ukr: "вночі", rus: "ночью", snd: "at night.mp3"});
DicArray.push({eng: "What time is it now?", trk: "|wɑːt taɪm ɪz ɪt naʊ?|", ukr: "Яка зараз година?", rus: "Который сейчас час?", snd: "What time is it now.mp3"});