var DicArray=[]; DicArray.push({eng: "top", trk: "|tɒp|", ukr: "верх", rus: "верх", snd: "top.mp3"});
DicArray.push({eng: "back", trk: "|ˈbæk|", ukr: "назад", rus: "назад", snd: "back.mp3"});
DicArray.push({eng: "forward", trk: "|ˈfɔːwəd|", ukr: "вперед", rus: "вперед", snd: "forward.mp3"});
DicArray.push({eng: "here", trk: "|hɪə|", ukr: "тут", rus: "здесь", snd: "here.mp3"});
DicArray.push({eng: "there", trk: "|ðɛː|", ukr: "там", rus: "там", snd: "there.mp3"});
DicArray.push({eng: "away", trk: "|əˈweɪ|", ukr: "далеко", rus: "далеко", snd: "away.mp3"});
DicArray.push({eng: "left", trk: "|left|", ukr: "лівий", rus: "левый", snd: "left.mp3"});
DicArray.push({eng: "right", trk: "|rʌɪt|", ukr: "правий ", rus: "правый", snd: "right.mp3"});
DicArray.push({eng: "front", trk: "|frʌnt|", ukr: "перед", rus: "перед", snd: "front.mp3"});
DicArray.push({eng: "middle", trk: "|ˈmɪdl|", ukr: "середина", rus: "середина", snd: "middle.mp3"});
DicArray.push({eng: "center", trk: "|ˈsentər|", ukr: "центр", rus: "центр", snd: "center.mp3"});
DicArray.push({eng: "bottom", trk: "|ˈbɒtəm|", ukr: "низ", rus: "низ", snd: "bottom.mp3"});
DicArray.push({eng: "side", trk: "|saɪd|", ukr: "сторона", rus: "сторона", snd: "side.mp3"});
DicArray.push({eng: "north", trk: "|nɔːθ|", ukr: "північ", rus: "север", snd: "north.mp3"});
DicArray.push({eng: "northern", trk: "|ˈnɔːrðərn|", ukr: "північний", rus: "северный", snd: "northern.mp3"});
DicArray.push({eng: "west", trk: "|west|", ukr: "захід", rus: "западный", snd: "west.mp3"});
DicArray.push({eng: "western", trk: "|ˈwestərn|", ukr: "західний", rus: "западный", snd: "western.mp3"});
DicArray.push({eng: "east", trk: "|iːst|", ukr: "схід", rus: "восток", snd: "east.mp3"});
DicArray.push({eng: "eastern", trk: "|ˈiːstərn|", ukr: "східний", rus: "восточный", snd: "eastern.mp3"});
DicArray.push({eng: "south", trk: "|saʊθ|", ukr: "південь", rus: "юг", snd: "south.mp3"});
DicArray.push({eng: "southern", trk: "|ˈsʌðərn|", ukr: "південний", rus: "южный", snd: "southern.mp3"});
DicArray.push({eng: "Russia", trk: "|ˈrʌʃə|", ukr: "Росія", rus: "Россия", snd: "Russia.mp3"});
DicArray.push({eng: "russian", trk: "|ˈrʌʃn|", ukr: "російський", rus: "российский", snd: "russian.mp3"});
DicArray.push({eng: "the United States of America", trk: "|ðə  juˈnaɪtɪd  steɪt  əv  əˈmer.ɪ.kə|", ukr: "США", rus: "США", snd: "the United States of America.mp3"});
DicArray.push({eng: "american", trk: "|əˈmerɪkən|", ukr: "американський", rus: "американский", snd: "american.mp3"});
DicArray.push({eng: "Canada", trk: "|ˈkanədə|", ukr: "Канада", rus: "Канада", snd: "Canada.mp3"});
DicArray.push({eng: "canadian", trk: "|kəˈneɪdiən|", ukr: "канадський", rus: "канадский", snd: "canadian.mp3"});
DicArray.push({eng: "Great Britain", trk: "|ɡreɪt   ˈbrɪt.ən|", ukr: "Великобрітанія", rus: "Великобритания ", snd: "Great Britain.mp3"});
DicArray.push({eng: "british", trk: "|ˈbrɪtɪʃ|", ukr: "британський", rus: "британский", snd: "british.mp3"});
DicArray.push({eng: "the British", trk: "|ðə  ˈbrɪt.ɪʃ|", ukr: "британці", rus: "британцы", snd: "the British.mp3"});
DicArray.push({eng: "english", trk: "|ˈɪŋɡlɪʃ|", ukr: "англійський", rus: "английский", snd: "english.mp3"});
DicArray.push({eng: "englishman", trk: "|ˈɪŋɡlɪʃmən|", ukr: "англієць", rus: "англичанин", snd: "englishman.mp3"});
DicArray.push({eng: "englishwoman", trk: "|ˈɪŋɡlɪʃwʊmən|", ukr: "англійка", rus: "англичанка", snd: "englishwoman.mp3"});
DicArray.push({eng: "England", trk: "|ˈɪŋɡlənd|", ukr: "Англія", rus: "Англия", snd: "England.mp3"});
DicArray.push({eng: "France", trk: "|frɑːns|", ukr: "Франція", rus: "Франция", snd: "France.mp3"});
DicArray.push({eng: "french", trk: "|frentʃ|", ukr: "французький", rus: "французский", snd: "french.mp3"});
DicArray.push({eng: "the French", trk: "|ðə  frentʃ |", ukr: "французи", rus: "французы", snd: "the French.mp3"});
DicArray.push({eng: "the English", trk: "|ðə   ˈɪŋ.ɡlɪʃ|", ukr: "англійці", rus: "англичане", snd: "the English.mp3"});
DicArray.push({eng: "frenchman", trk: "|ˈfrentʃmən|", ukr: "француз", rus: "француз", snd: "frenchman.mp3"});
DicArray.push({eng: "frenchwoman", trk: "|ˈfrentʃwʊmən|", ukr: "француженка", rus: "француженка", snd: "frenchwoman.mp3"});
DicArray.push({eng: "Germany", trk: "|ˈdʒɜːrməni|", ukr: "Німеччина", rus: "Германия ", snd: "Germany.mp3"});
DicArray.push({eng: "german", trk: "|ˈdʒəːmən|", ukr: "німецький", rus: "немецкий", snd: "german.mp3"});
DicArray.push({eng: "Italy", trk: "|ˈɪtəli|", ukr: "Італія", rus: "Италия", snd: "Italy.mp3"});
DicArray.push({eng: "italian", trk: "|ɪˈtaljən|", ukr: "італійський", rus: "итальянский", snd: "italian.mp3"});
DicArray.push({eng: "Japan", trk: "|dʒəˈpan|", ukr: "Японія", rus: "Япония", snd: "Japan.mp3"});
DicArray.push({eng: "japanese", trk: "|ˌdʒæpəˈniːz|", ukr: "японський", rus: "японский", snd: "japanese.mp3"});
DicArray.push({eng: "Ukraine", trk: "|juːˈkreɪn|", ukr: "Україна", rus: "Украина", snd: "Ukraine.mp3"});
DicArray.push({eng: "ukrainian", trk: "|juːˈkreɪnɪən|", ukr: "український", rus: "украинский", snd: "ukrainian.mp3"});