var DicArray=[]; DicArray.push({eng: "place", trk: "|pleɪs|", ukr: "місце", rus: "место", snd: "place.mp3"});
DicArray.push({eng: "direction", trk: "|dəˈrekʃn|", ukr: "напрямок", rus: "направление", snd: "direction.mp3"});
DicArray.push({eng: "up", trk: "|ʌp|", ukr: "вгору", rus: "вверх", snd: "up.mp3"});
DicArray.push({eng: "to", trk: "|tuː|", ukr: "до", rus: "к", snd: "to.mp3"});
DicArray.push({eng: "into", trk: "|ˈɪntə|", ukr: "в", rus: "в", snd: "into.mp3"});
DicArray.push({eng: "at", trk: "|æt|", ukr: "у, в, на", rus: "у, в, на", snd: "at.mp3"});
DicArray.push({eng: "down", trk: "|daʊn|", ukr: "вниз", rus: "вниз", snd: "down.mp3"});
DicArray.push({eng: "over", trk: "|ˈəʊvə|", ukr: "над", rus: "над", snd: "over.mp3"});
DicArray.push({eng: "on", trk: "|ɒn|", ukr: "на", rus: "на", snd: "on.mp3"});
DicArray.push({eng: "in", trk: "|ɪn|", ukr: "в", rus: "в", snd: "in.mp3"});
DicArray.push({eng: "under", trk: "|ˈʌndə|", ukr: "під", rus: "под", snd: "under.mp3"});
DicArray.push({eng: "above", trk: "|əˈbʌv|", ukr: "вище, над", rus: "выше, над", snd: "above.mp3"});
DicArray.push({eng: "off", trk: "|ɒf|", ukr: "з (поверхні)", rus: "с (поверхности)", snd: "off.mp3"});
DicArray.push({eng: "from", trk: "|frɒm|", ukr: "від, із", rus: "от, из", snd: "from.mp3"});
DicArray.push({eng: "out (of)", trk: "|ˈaʊt|", ukr: "із (чого)", rus: "из (чего)", snd: "out (of).mp3"});
DicArray.push({eng: "below", trk: "|bɪˈləʊ|", ukr: "нижче, під", rus: "ниже, под", snd: "below.mp3"});
DicArray.push({eng: "close", trk: "|kləʊs|", ukr: "близько", rus: "близко", snd: "close.mp3"});
DicArray.push({eng: "near", trk: "|nɪə|", ukr: "поряд", rus: "рядом", snd: "near.mp3"});
DicArray.push({eng: "far (from)", trk: "|ˈfɑː|", ukr: "далеко (від)", rus: "далеко (от)", snd: "far (from).mp3"});
DicArray.push({eng: "a long way (from)", trk: "|lɔːŋ ˈweɪ|", ukr: "далеко (від)", rus: "далеко (от)", snd: "long way (from).mp3"});
DicArray.push({eng: "in front", trk: "|ɪn frʌnt|", ukr: "попереду", rus: "перед", snd: "in front.mp3"});
DicArray.push({eng: "behind", trk: "|bɪˈhʌɪnd|", ukr: "позаду", rus: "позади", snd: "behind.mp3"});
DicArray.push({eng: "around", trk: "|əˈraʊnd|", ukr: "навколо", rus: "вокруг", snd: "around.mp3"});
DicArray.push({eng: "across", trk: "|əˈkrɒs|", ukr: "через", rus: "через", snd: "across.mp3"});
DicArray.push({eng: "through", trk: "|θruː|", ukr: "крізь", rus: "насквозь", snd: "through.mp3"});
DicArray.push({eng: "outside", trk: "|ˌaʊtˈsaɪd|", ukr: "назовні", rus: "снаружи", snd: "outside.mp3"});
DicArray.push({eng: "inside", trk: "|ˌɪnˈsaɪd|", ukr: "всередині", rus: "внутри", snd: "inside.mp3"});
DicArray.push({eng: "along", trk: "|əˈlɒŋ|", ukr: "уздовж", rus: "вдоль", snd: "along.mp3"});
DicArray.push({eng: "next to", trk: "|nekst|", ukr: "поруч з", rus: "рядом", snd: "next to.mp3"});
DicArray.push({eng: "by", trk: "|baɪ|", ukr: "коло", rus: "около", snd: "by.mp3"});
DicArray.push({eng: "beside", trk: "|bɪˈsʌɪd|", ukr: "поруч", rus: "рядом ", snd: "beside.mp3"});
DicArray.push({eng: "all over", trk: "|ɔːl ˈəʊvə|", ukr: "повсюди", rus: "по всему", snd: "all over.mp3"});
DicArray.push({eng: "between", trk: "|bɪˈtwiːn|", ukr: "між", rus: "между", snd: "between.mp3"});
DicArray.push({eng: "among", trk: "|əˈmʌŋ|", ukr: "серед", rus: "среди", snd: "among.mp3"});