var DicArray=[]; DicArray.push({eng: "pair", trk: "|peə|", ukr: "пара", rus: "пара", snd: "pair.mp3"});
DicArray.push({eng: "couple", trk: "|ˈkʌpl|", ukr: "пара, два", rus: "пара, два", snd: "couple.mp3"});
DicArray.push({eng: "dozen", trk: "|ˈdʌzn|", ukr: "дюжина", rus: "дюжина", snd: "dozen.mp3"});
DicArray.push({eng: "half", trk: "|hɑːf|", ukr: "половина", rus: "половина", snd: "half.mp3"});
DicArray.push({eng: "quarter", trk: "|ˈkwɔːrtər|", ukr: "четверть", rus: "четверть", snd: "quarter.mp3"});
DicArray.push({eng: "next", trk: "|nekst|", ukr: "наступний", rus: "следующий", snd: "next.mp3"});
DicArray.push({eng: "following", trk: "|ˈfɑːloʊɪŋ|", ukr: "наступний", rus: "следующий", snd: "following.mp3"});
DicArray.push({eng: "previous", trk: "|ˈpriːvɪəs|", ukr: "попередній", rus: "предыдущий", snd: "previous.mp3"});
DicArray.push({eng: "last", trk: "|lɑːst|", ukr: "останній", rus: "последний", snd: "last.mp3"});
DicArray.push({eng: "many books", trk: "|ˈmeni  bʊks|", ukr: "багато книг", rus: "много книг", snd: "many books.mp3"});
DicArray.push({eng: "a few books", trk: "|eɪ  fjuː  bʊks|", ukr: "кілька книг", rus: "несколько книг", snd: "a few books.mp3"});
DicArray.push({eng: "few books", trk: "|fjuː  bʊks|", ukr: "мало книг", rus: "мало книг", snd: "few books.mp3"});
DicArray.push({eng: "much milk", trk: "|mʌtʃ  mɪlk|", ukr: "багато молока", rus: "много молока", snd: "much milk.mp3"});
DicArray.push({eng: "a little milk", trk: "|eɪ ˈlɪtl  mɪlk|", ukr: "трохи молока", rus: "немного молока", snd: "a little milk.mp3"});
DicArray.push({eng: "little milk", trk: "|ˈlɪtl  mɪlk|", ukr: "мало молока", rus: "мало молока", snd: "little milk.mp3"});
DicArray.push({eng: "a lot of", trk: "|eɪ  lɑːt  əv|", ukr: "багато", rus: "много", snd: "a lot of.mp3"});
DicArray.push({eng: "lots of", trk: "|lɑːts  əv |", ukr: "багато", rus: "много", snd: "lots of.mp3"});
DicArray.push({eng: "plenty of", trk: "|ˈplenti  əv|", ukr: "багато, вволю", rus: "в изобилии", snd: "plenty of.mp3"});
DicArray.push({eng: "enough", trk: "|ɪˈnʌf|", ukr: "достатньо", rus: "достаточно", snd: "enough.mp3"});
DicArray.push({eng: "some", trk: "|sʌm|", ukr: "деяка кількість", rus: "некоторое количество", snd: "some.mp3"});
DicArray.push({eng: "a a number of", trk: "|eɪ  ˈnʌmbər  əv|", ukr: "деяка кількість", rus: " некоторое количество", snd: "a number of.mp3"});