var DicArray=[];

DicArray.push({eng: "lip", trk: "|lɪp|", ukr: "губа", rus: "губа", snd: "lip.mp3"});
DicArray.push({eng: "he", trk: "|hi|", ukr: "він", rus: "он", snd: "he.mp3"});
DicArray.push({eng: "green", trk: "|ɡriːn|", ukr: "зелений", rus: "зеленый", snd: "green.mp3"});
DicArray.push({eng: "read", trk: "|riːd|", ukr: "читати", rus: "читать", snd: "read.mp3"});
DicArray.push({eng: "field", trk: "|fiːld|", ukr: "поле", rus: "поле", snd: "field.mp3"});
DicArray.push({eng: "receive", trk: "|rɪˈsiːv|", ukr: "отримувати", rus: "получать", snd: "receive.mp3"});
DicArray.push({eng: "set", trk: "|set|", ukr: "встановити", rus: "устанавливать", snd: "set.mp3"});
DicArray.push({eng: "bag", trk: "|bæɡ|", ukr: "сумка", rus: "сумка", snd: "bag.mp3"});
DicArray.push({eng: "bar", trk: "|bɑː|", ukr: "бар", rus: "бар", snd: "bar.mp3"});
DicArray.push({eng: "class", trk: "|klɑːs|", ukr: "клас", rus: "класс", snd: "class.mp3"});
DicArray.push({eng: "past", trk: "|pɑːst|", ukr: "минуле", rus: "прошлое", snd: "past.mp3"});
DicArray.push({eng: "task", trk: "|tɑːsk|", ukr: "задача", rus: "задача", snd: "task.mp3"});
DicArray.push({eng: "plant", trk: "|plɑːnt|", ukr: "завод", rus: "завод", snd: "plant.mp3"});
DicArray.push({eng: "heart", trk: "|hɑːt|", ukr: "серце", rus: "сердце", snd: "heart.mp3"});
DicArray.push({eng: "not", trk: "|nɒt|", ukr: "ні", rus: "нет", snd: "not.mp3"});
DicArray.push({eng: "what", trk: "|ˈwɒt|", ukr: "що", rus: "что", snd: "what.mp3"});
DicArray.push({eng: "quality", trk: "|ˈkwɒlɪti|", ukr: "якість", rus: "качество", snd: "quality.mp3"});
DicArray.push({eng: "short", trk: "|ʃɔːt|", ukr: "короткий", rus: "короткий", snd: "short.mp3"});
DicArray.push({eng: "small", trk: "|smɔːl|", ukr: "маленький", rus: "маленький", snd: "small.mp3"});
DicArray.push({eng: "cause", trk: "|kɔːz|", ukr: "причина", rus: "причина", snd: "cause.mp3"});
DicArray.push({eng: "law", trk: "|lɔː|", ukr: "закон", rus: "закон", snd: "law.mp3"});
DicArray.push({eng: "daughter", trk: "|ˈdɔːtə|", ukr: "дочка", rus: "дочка", snd: "daughter.mp3"});
DicArray.push({eng: "thought", trk: "|θɔːt|", ukr: "думка", rus: "мысль", snd: "thought.mp3"});
DicArray.push({eng: "warm", trk: "|wɔːm|", ukr: "теплий", rus: "теплый", snd: "warm.mp3"});