var DicArray=[];

//clothes
DicArray.push({eng: "clothes", ukr: "одяг", rus: "одежда", trk: "|kləʊ(ð)z|", snd: "clothes.mp3"});
DicArray.push({eng: "shirt", ukr: "сорочка", rus: "рубашка", trk: "|ʃəːt|", snd: "shirt.mp3"});
DicArray.push({eng: "tie", ukr: "краватка", rus: "галстук", trk: "|taɪ|", snd: "tie.mp3"});
DicArray.push({eng: "suit", ukr: "костюм", rus: "костюм", trk: "|suːt|", snd: "suit.mp3"});
DicArray.push({eng: "pocket", ukr: "кишеня", rus: "карман", trk: "|ˈpɒkɪt|", snd: "pocket.mp3"});
DicArray.push({eng: "trousers", ukr: "штани", rus: "брюки", trk: "|ˈtraʊzəz|", snd: "trousers.mp3"});
DicArray.push({eng: "hat", ukr: "капелюх", rus: "шляпа", trk: "|hæt|", snd: "hat.mp3"});
DicArray.push({eng: "blouse", ukr: "блузка", rus: "блузка", trk: "|ˈblaʊz|", snd: "blouse.mp3"});
DicArray.push({eng: "jacket", ukr: "куртка, піджак", rus: "куртка, жакет", trk: "|ˈdʒakɪt|", snd: "jacket.mp3"});
DicArray.push({eng: "bag", ukr: "сумка", rus: "мешок, сумка", trk: "|bæɡ|", snd: "bag.mp3"});
DicArray.push({eng: "skirt", ukr: "спідниця", rus: "юбка", trk: "|skəːt|", snd: "skirt.mp3"});
DicArray.push({eng: "dress", ukr: "плаття", rus: "платье", trk: "|drɛs|", snd: "dress.mp3"});
DicArray.push({eng: "coat", ukr: "пальто", rus: "пальто", trk: "|ˈkəʊt|", snd: "coat.mp3"});
DicArray.push({eng: "shoe", ukr: "туфля", rus: "туфля", trk: "|ʃuː|", snd: "shoe.mp3"});     //Food
DicArray.push({eng: "food", ukr: "їжа", rus: "еда", trk: "|fuːd|", snd: "food.mp3"});
DicArray.push({eng: "drink", ukr: "напій", rus: "напиток", trk: "|drɪŋk|", snd: "drink.mp3"});
DicArray.push({eng: "bottle", ukr: "пляшка", rus: "бутылка", trk: "|ˈbɒt(ə)l|", snd: "bottle.mp3"});
DicArray.push({eng: "juice", ukr: "сік", rus: "сок", trk: "|dʒuːs|", snd: "juice.mp3"});
DicArray.push({eng: "water", ukr: "вода", rus: "вода", trk: "|ˈwɔːtə|", snd: "water.mp3"});
DicArray.push({eng: "ice", ukr: "лід", rus: "лед", trk: "|aɪs|", snd: "ice.mp3"});
DicArray.push({eng: "glass", ukr: "стакан", rus: "стакан", trk: "|ɡlɑːs|", snd: "glass.mp3"});
DicArray.push({eng: "milk", ukr: "молоко", rus: "молоко", trk: "|mɪlk|", snd: "milk.mp3"});
DicArray.push({eng: "bread", ukr: "хліб", rus: "хлеб", trk: "|brɛd|", snd: "bread.mp3"});
DicArray.push({eng: "vegetable", ukr: "овоч", rus: "овощ", trk: "|ˈvɛdʒtəb(ə)l|", snd: "vegetable.mp3"});
DicArray.push({eng: "fruit", ukr: "фрукт", rus: "фрукт", trk: "|fruːt|", snd: "fruit.mp3"});
DicArray.push({eng: "chicken", ukr: "курча", rus: "цыплёнок", trk: "|ˈtʃɪkɪn|", snd: "chicken.mp3"});
DicArray.push({eng: "salt", ukr: "сіль", rus: "соль", trk: "|sɔːlt|", snd: "salt.mp3"});
DicArray.push({eng: "tea", ukr: "чай", rus: "чай", trk: "|tiː|", snd: "tea.mp3"});
DicArray.push({eng: "cheese", ukr: "сир", rus: "сыр", trk: "|tʃiːz|", snd: "cheese.mp3"});
DicArray.push({eng: "butter", ukr: "масло", rus: "масло", trk: "|ˈbʌtə|", snd: "butter.mp3"});
DicArray.push({eng: "sugar", ukr: "цукор", rus: "сахар", trk: "|ˈʃʊɡə|", snd: "sugar.mp3"});
DicArray.push({eng: "meat", ukr: "м'ясо", rus: "мясо", trk: "|miːt|", snd: "meat.mp3"});
DicArray.push({eng: "fish", ukr: "риба", rus: "рыба", trk: "|fɪʃ|", snd: "fish.mp3"});
DicArray.push({eng: "sweets", ukr: "солодощі", rus: "сладости", trk: "|swiːt|", snd: "sweets.mp3"});
DicArray.push({eng: "spoon", ukr: "ложка", rus: "ложка", trk: "|spuːn|", snd: "spoon.mp3"});
DicArray.push({eng: "knife", ukr: "ніж", rus: "нож", trk: "|nʌɪf|", snd: "knife.mp3"});
DicArray.push({eng: "fork", ukr: "вилка", rus: "вилка", trk: "|fɔːk|", snd: "fork.mp3"});
DicArray.push({eng: "cup", ukr: "чашка", rus: "чашка", trk: "|kʌp|", snd: "cup.mp3"});
DicArray.push({eng: "saucer", ukr: "блюдце", rus: "блюдце", trk: "|ˈsɔːsə|", snd: "saucer.mp3"});
DicArray.push({eng: "plate", ukr: "тарілка", rus: "тарелка", trk: "|pleɪt|", snd: "plate.mp3"}); //Письмовий стіл
DicArray.push({eng: "thing", ukr: "річ", rus: "вещь", trk: "|θɪŋ|", snd: "thing.mp3"});
DicArray.push({eng: "picture", ukr: "картина", rus: "картина", trk: "|ˈpɪktʃə|", snd: "picture.mp3"});
DicArray.push({eng: "portrait", ukr: "портрет", rus: "портрет", trk: "|ˈpɔːtrət|", snd: "portrait.mp3"});
DicArray.push({eng: "lamp", ukr: "лампа", rus: "лампа", trk: "|læmp|", snd: "lamp.mp3"});
DicArray.push({eng: "light", ukr: "світло", rus: "свет", trk: "|lʌɪt|", snd: "light.mp3"});
DicArray.push({eng: "paper", ukr: "папір", rus: "бумага", trk: "|ˈpeɪpə|", snd: "paper.mp3"});
DicArray.push({eng: "book", ukr: "книга", rus: "книга", trk: "|bʊk|", snd: "book.mp3"});
DicArray.push({eng: "page", ukr: "сторінка", rus: "страница", trk: "|peɪdʒ|", snd: "page.mp3"});
DicArray.push({eng: "fire", ukr: "вогонь", rus: "огонь", trk: "|ˈfaɪə|", snd: "fire.mp3"});
DicArray.push({eng: "sound", ukr: "звук", rus: "звук", trk: "|saʊnd|", snd: "sound.mp3"});
DicArray.push({eng: "shadow", ukr: "тінь", rus: "тень", trk: "|ˈʃadəʊ|", snd: "shadow.mp3"});
DicArray.push({eng: "spectacles", ukr: "окуляри", rus: "очки", trk: "|ˈspɛktək(ə)lz|", snd: "spectacles.mp3"});
DicArray.push({eng: "money", ukr: "гроші", rus: "деньги", trk: "|ˈmʌni|", snd: "money.mp3"});
DicArray.push({eng: "pen", ukr: "ручка", rus: "ручка", trk: "|pen|", snd: "pen.mp3"});
DicArray.push({eng: "pencil", ukr: "олівець", rus: "карандаш", trk: "|ˈpɛns(ə)l|", snd: "pencil.mp3"});
DicArray.push({eng: "air", ukr: "повітря", rus: "воздух", trk: "|eə|", snd: "air.mp3"});